//
//  SafeTTesting2.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class SafeTTesting2: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _Latitude: String?
    var _Longitude: String?
    var _Type: String?
    var _Emergency: String?
    var _Building: String?
    //var _Safe: String?
    //var _Active: String?
    var _Time: String?
    //var _Speed: String?
    
    class func dynamoDBTableName() -> String {

        return "safet-mobilehub-905430148-SafeT_Testing2"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_Latitude" : "Latitude",
               "_Longitude" : "Longitude",
               "_Type" : "Type",
               "_Time" : "Time",
               "_Building" : "Building",
               "_Emergency" : "Emergency"
        ]
    }
}
